name: "Install dependencias"
description: "Comprimir archivos"
runs:
  using: "composite"
  steps:
    - name: Install dependencias
      shell: pwsh
      run: |
          npm install -g @angular/cli
          npm install