name: WorkflowAngular

run-name: "CI/CD-Angular"

on:
  push:
    branches:
      - main

jobs:
  compilacion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set version node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: |
          npm install -g @angular/cli
          npm install

      - name: compilacion
        run: ng build --configuration production  

      - name: Crear zip de proyecto 
        uses: ./.github/actions/createzip
        with:
          source: dist/my-first-angular-app/browser
          output: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: compilacion
    environment: DEV
    steps:
      - name: Prueba echo
        run: echo "Deploy"      